version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
jobs:
  build:
    docker:
      - image: 'circleci/python:3.8.8'
    steps:
    - checkout
    - sonarcloud/scan
workflows:
  my-workflow:
    jobs:
      - build:
          context: sonarcloud
